<a href="https://colab.research.google.com/github/Abhisekh97/pythorch-tutorial/blob/main/linear_regrssion_in_ptorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch


In [95]:
import numpy as np
import torch as pt

In [96]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [97]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [98]:
inputs = pt.from_numpy(inputs)

In [99]:
targets = pt.from_numpy(targets)

In [111]:
w = pt.randn(2,3, requires_grad=True)
b = pt.randn(2, requires_grad=True)

In [101]:
print(w)

tensor([[-0.4834, -0.5801, -0.4193],
        [ 1.0051,  0.5252, -1.1974]], requires_grad=True)


In [102]:
def model(inputs):
  return inputs @ w.t() + b

In [103]:
print(output)

tensor([[  9.4070,  42.3052],
        [ 13.6799,  56.5922],
        [ 66.6268,  76.9514],
        [-34.0306,  31.0458],
        [ 35.4556,  60.6044]], grad_fn=<AddBackward0>)


In [104]:
prediction = model(inputs)

In [105]:
print(prediction)

tensor([[ -93.4299,   56.9226],
        [-123.1189,   60.9000],
        [-145.3562,   88.2236],
        [ -91.0096,   80.6507],
        [-119.6408,   35.8044]], grad_fn=<AddBackward0>)


In [106]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [107]:
def rmse_loss(pred, targets):
  diff = pred - targets
  diff = diff * diff
  su = pt.sum(diff)/diff.numel()
  return pt.sqrt(su)

In [112]:
for i in range(1000):
  predictions = model(inputs)
  loss = rmse_loss(predictions, targets)
  if i%100 == 0:
    print(" epoch {} loss: {}\n".format(i+1, loss))
  loss.backward()
  with pt.no_grad():
    w -= w.grad * 1e-3
    b -= b.grad * 1e-3
    w.grad.zero_()
    b.grad.zero_()

 epoch 1 loss: 115.27461242675781

 epoch 101 loss: 17.625932693481445

 epoch 201 loss: 4.468225479125977

 epoch 301 loss: 4.4765424728393555

 epoch 401 loss: 4.47726583480835

 epoch 501 loss: 4.477347373962402

 epoch 601 loss: 4.477368354797363

 epoch 701 loss: 4.477360248565674

 epoch 801 loss: 4.477365493774414

 epoch 901 loss: 4.47736120223999



In [114]:
print(w)

tensor([[-0.4008,  0.8590,  0.6852],
        [-0.3409,  0.7655,  0.8827]], requires_grad=True)


In [115]:
print(b)

tensor([1.3726, 1.4920], requires_grad=True)


In [116]:
pred = model(inputs)

In [117]:
print(pred)
print(targets)

tensor([[ 59.1362,  65.8471],
        [ 84.3519,  94.3223],
        [121.3583, 125.6007],
        [ 22.7859,  32.2926],
        [104.1525, 113.2430]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [118]:
!pip install jovian --upgrade -q

     |████████████████████████████████| 71kB 3.0MB/s 


In [119]:
import jovian

In [120]:
jovian.commit(project='02-linear-regression')

[jovian] Detected Colab notebook...


[jovian] Error: jovian.commit doesn't work on Colab unless the notebook was created and executed from Jovian.
Make sure to run the first code cell at the top after executing from Jovian.
Alternatively, you can download this notebook and upload it manually to Jovian.
Learn more: https://jovian.ai/docs/user-guide/run.html#run-on-colab
